---
global_config:
  environment_name: deployer-demo
  cloud_platform: aws
  aws_region: eu-central-1

vault:
  vault_type: ibmcloud-vault
  vault_authentication_type: api-key
  vault_url: https://caabac85-40ab-40d5-965a-a7e9debd5e37.eu-de.secrets-manager.appdomain.cloud

nfs_server:
- name: deployer-demo-elastic
  infrastructure:
    aws_region: "{{ aws_region }}"

openshift:
- name: deployer-aws
  domain_name: deployer-demo.eu
  ocp_version: 4.10.41
  control_plane_flavour: m5.xlarge
  control_plane_nodes: 3
  compute_flavour: m5.4xlarge
  compute_nodes: 3
  console_banner: "cp4d 4.6.6 AWS"
  oadp: True
  infrastructure:
    type: self-managed
    aws_region: "{{ aws_region }}"
    multi_zone: False
    use_sts: False
    machine_cidr: 10.1.0.0/24
  openshift_storage:
  - storage_name: deployer-demo-elastic
    storage_type: aws-elastic