name: Cloud Pak Deployer git flow

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clone the deployer repo
      - name: Clone the deployer repo
        run: |
          cd ~
          rm -rf ~/cloud-pak-deployer
          git clone https://github.com/IBM/cloud-pak-deployer.git
          
      # Build the deployer
      - name: Build the deployer
        run: |
          cd ~/cloud-pak-deployer
          ./cp-deploy.sh build

  configure:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve the configuration
        uses: actions/checkout@v3
        
      - name: Show the configuration directory
        run: |
          echo $PWD
          ls -lR
        
      - name: Set vault secrets
        env:
          OCP_PULLSECRET: ${{ secrets.OCP_PULLSECRET }}
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
        run: |
          echo $OCP_PULLSECRET > ~/cpd-config/ocp_pullsecret.json
          ~/cloud-pak-deployer/cp-deploy.sh vault set -vs ocp-pullsecret -vsf ~/cpd-config/ocp_pullsecret.json
                  
      - name: List vault secrets
        run: |
          ~/cloud-pak-deployer/cp-deploy.sh vault list
          
  check-configuration:
    needs: configure
    runs-on: ubuntu-latest

    steps:
      - name: Check configuration
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CP_ENTITLEMENT_KEY: ${{ secrets.CP_ENTITLEMENT_KEY }}
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
        run: |
          ~/cloud-pak-deployer/cp-deploy.sh env apply --check-only

  deploy:
    needs: check-configuration
    runs-on: ubuntu-latest

    steps:
      - name: Run deployment (OpenShift only)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CP_ENTITLEMENT_KEY: ${{ secrets.CP_ENTITLEMENT_KEY }}
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
        run: |
          ~/cloud-pak-deployer/cp-deploy.sh env apply -v
