name: test-deployer

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:

      # Log secret
      - name: Log secret
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: |
          echo "Access key ID: $AWS_ACCESS_KEY_ID"

      # Clone the deployer repo
      - name: Clone the deployer repo
        run: |
          cd ~
          rm -rf ~/cloud-pak-deployer
          git clone https://github.com/IBM/cloud-pak-deployer.git
          
      # Build the deployer
      - name: Build the deployer
        run: |
          cd ~/cloud-pak-deployer
          ./cp-deploy.sh build
          
